import Head from "next/head";
import Navbar from "../components/navbar";
import Info from "../components/info";
import Proposals from "../components/proposals";
import FetchComponent from "../components/fetch.jsx"
import {useState,useEffect} from 'react';
import { useMoralis, useMoralisWeb3Api, useWeb3ExecuteFunction} from "react-moralis";

export default function Home() {
  const { Moralis, isInitialized } = useMoralis();
  const Web3Api=useMoralisWeb3Api();


  const [proposals, setProposals] = useState([]);
  const [totalP, setTotalP] = useState();
  const [voters, setVoters] = useState();

  



  useEffect(() => {
    if (isInitialized) {
      async function getProposals() {
        const CreatedProposals = Moralis.Object.extend("CreatedProposals");
        const query = new Moralis.Query(CreatedProposals);
        query.descending("uid_decimal");
        const results = await query.find();
        const table = await Promise.all(
          results.map(async (e) => [
            e.attributes.uid,
            e.attributes.description,
            e.attributes.confirmed,
          ])
        );
        setProposals(table);
        setTotalP(results.length);
      }
      
  const fetchTokenOwners= async ()=>{
    const options={
      address:"0x88B48F654c30e99bc2e4A1559b4Dcf1aD93FA656",
      token_id:"58538135596029509329456146620683606546470122578009882867137711147461097029832",
      chain:"rinkeby"
    }
    
    const tokenIdOwners= await Web3Api.token.getTokenIdOwners(options);
    const addresses= tokenIdOwners.result.map((e)=>e.owner_of);
    setVoters(addresses);
      }
    


      fetchTokenOwners();
      getProposals();

    
    }
  }, [isInitialized]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <Navbar />
          <Info totalP={totalP} voters={voters} />
          <Proposals proposals={proposals} voters={voters}  />
        <FetchComponent/>
        </div>
      </main>
    </div>
  );
}
